
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  # Exposes frontend
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"  # Exposes backend (update to match Django's port)
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings  # Update if needed
    volumes:
      - ./backend:/app  # Ensures SQLite data persists in the backend directory
