# Generated by Django 5.1.1 on 2024-10-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_remove_recruiter_user_recruiter_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='experience',
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
