# Generated by Django 5.0.6 on 2024-10-25 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_user_groups_user_is_superuser_user_last_login_and_more'),
        ('signup', '0007_remove_profile_experience_candidate_experience'),
    ]

    operations = [
    ]
