# Generated by Django 5.0.6 on 2024-11-13 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_remove_candidate_experience_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('workplace_type', models.CharField(choices=[('remote', 'Remote'), ('on_site', 'On Site'), ('hybrid', 'Hybrid')], max_length=10)),
                ('job_location', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship')], max_length=10)),
                ('description', models.TextField()),
                ('skills', models.TextField(help_text='Comma-separated list of skills required for the job')),
                ('interview_type', models.CharField(choices=[('ai', 'AI'), ('manual', 'Manual')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='signup.recruiter')),
            ],
        ),
    ]
