# Generated by Django 5.0.6 on 2024-11-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0010_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
    ]
