# Generated by Django 5.0.6 on 2024-11-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0012_alter_job_employment_type_alter_job_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('internship', 'Internship')], max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.CharField(choices=[('front-end', 'Front-end'), ('back-end', 'Back-end'), ('full stack', 'Full Stack'), ('app development', 'App Development'), ('db administrator', 'DB Administrator')], max_length=20),
        ),
    ]
