# Generated by Django 5.0.6 on 2024-11-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0013_alter_job_employment_type_alter_job_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract')], max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.CharField(choices=[('App Development', 'App Development'), ('Data Science', 'Data Science')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='workplace_type',
            field=models.CharField(choices=[('Remote', 'Remote'), ('On-site', 'On-site'), ('Hybrid', 'Hybrid')], max_length=10),
        ),
    ]
