# Generated by Django 5.0.6 on 2024-11-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0016_alter_job_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.CharField(choices=[('Front-end', 'Front-end'), ('Back-end', 'Back-end'), ('Full Stack', 'Full Stack'), ('App Development', 'App Development'), ('DB Administrator', 'DB Administrator')], max_length=20),
        ),
    ]
