# Generated by Django 5.0.6 on 2024-11-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0017_alter_job_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='workplace_type',
            field=models.CharField(choices=[('Remote', 'Remote'), ('On-site', 'On site'), ('Hybrid', 'Hybrid')], max_length=10),
        ),
    ]
