# Generated by Django 5.0.6 on 2024-11-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0019_alter_job_workplace_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscription',
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='is_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
