# Generated by Django 5.0.6 on 2024-11-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0020_remove_user_is_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='is_subscription',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='subscription_end_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='subscription_start_date',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='is_subscription',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='subscription_end_date',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='subscription_start_date',
        ),
        migrations.AddField(
            model_name='user',
            name='is_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
