# Generated by Django 5.0.6 on 2024-11-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0022_remove_user_is_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
