# Generated by Django 5.0.6 on 2024-12-04 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0025_report_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='signup.user'),
            preserve_default=False,
        ),
    ]
