# Generated by Django 5.0.6 on 2024-12-11 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0027_alter_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.user'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'type')},
        ),
    ]
