# Generated by Django 5.0.6 on 2025-01-14 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0029_savedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='signup.user'),
        ),
    ]
